apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{ .Values.global.storage_class }}


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: {{ .Values.global.storage_class }}